couchbase:
  image: registry.virtusacloud.net:5000/couch_base
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210
  #volumes_from:
   # - linking_volume_couchbase
  environment:
    BUCKET: sensor
    CB_USER: Administrator
    CB_PASS: password
couchdb:
  image: registry.virtusacloud.net:5000/couchdb
  ports:
    - 5984:5984
  links:
    - couchbase
 #   - sync_gateway
syncgateway:
  image: registry.virtusacloud.net:5000/syncgateway
  ports:
    - 4984:4984
    - 4985:4985
  links:
    - couchbase
talend :
  tty: true
  stdin_open: true
  image: registry.virtusacloud.net:5000/talend
